version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 of the host
    volumes:
      - ./frontend:/app
    depends_on:
      - backend